# -*- coding: utf-8 -*-
"""semantic_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAhZ32WDtkZqwiQ2ca4aDcsUVeVPpsLA
"""

"""
semantic_utils.py
Вспомогательные функции для семантического анализа.
Используется в semantic_w2v.py, semantic_adagram.py, semantic_rubert.py.
"""

from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("Agg")  # чтоб не открывало окошки
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# параметры для топ-k и порогов
top_k_values = [1, 5, 10, 20, 50, 100]
nn_thresholds = [0.70, 0.80, 0.90]

# стили для графиков (чтоб красиво было)
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 10,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "grid.linestyle": "--",
    "figure.dpi": 150,
})

# стили для разных подходов (линия, маркер, цвет)
approach_styles = {
    "word2vec":  ("-",  "o", "#2B6CB0"),
    "adagram":   ("--", "s", "#276749"),
    "rubert_A":  ("-",  "^", "#553C9A"),
    "rubert_B":  ("--", "D", "#805AD5"),
    "rubert_C":  (":",  "P", "#B794F4"),
}



# функции для всех метрик, чтобы не перегружать другие тетрадки

def normalize_rows(m: np.ndarray) -> np.ndarray:
    """Нормализуем строки матрицы (чтоб были единичной длины)"""
    norms = np.linalg.norm(m, axis=1, keepdims=True)
    return m / (norms + 1e-9)  # добавляем маленькое число чтоб не делить на ноль


def weighted_centroid(vecs: np.ndarray, probs: np.ndarray) -> np.ndarray:
    """Считаем взвешенный центроид векторов"""
    c = (probs[:, None] * vecs).sum(axis=0)
    return c / (np.linalg.norm(c) + 1e-9)


def centroid_sim(h_vecs, h_probs, m_vecs, m_probs) -> float:
    """Косинусное сходство между центроидами людей и модели"""
    return float(np.dot(weighted_centroid(h_vecs, h_probs),
                        weighted_centroid(m_vecs, m_probs)))


def nn_recall(h_probs: np.ndarray, sim_matrix: np.ndarray, thr: float) -> float:
    """Доля вероятностной массы людей, которую покрыла модель"""
    best = sim_matrix.max(axis=1)  # для каждого человека - лучший кандидат из модели
    return float(np.dot(h_probs, (best >= thr).astype(float)))


def nn_precision(m_probs: np.ndarray, sim_matrix: np.ndarray, thr: float) -> float:
    """Доля вероятностной массы модели, которую покрыли люди"""
    best = sim_matrix.max(axis=0)  # для каждого кандидата модели - лучший человек
    return float(np.dot(m_probs, (best >= thr).astype(float)))


def f1_score(precision: float, recall: float) -> float:
    """Среднее гармоническое точности и полноты"""
    if precision + recall < 1e-9:
        return 0.0
    return 2 * precision * recall / (precision + recall)


def compute_metrics(h_vecs: np.ndarray, h_probs: np.ndarray,
                    m_vecs_all: np.ndarray, m_probs_all: np.ndarray,
                    top_k: int) -> dict:
    """
    Считаем все метрики для одного контекста и одного top_k
    """
    k_eff = min(top_k, len(m_vecs_all))  # эффективное k (не больше чем есть)

    # берем top-k предсказаний модели
    mv = normalize_rows(m_vecs_all[:k_eff])
    mp = m_probs_all[:k_eff].copy()
    mp /= mp.sum() + 1e-9  # нормализуем вероятности

    # векторы людей тоже нормализуем
    hv = normalize_rows(h_vecs)
    hp = h_probs.copy()
    hp /= hp.sum() + 1e-9

    # матрица сходств
    sim = hv @ mv.T  # (n_human, k_eff)

    # собираем результаты в словарь
    res = {
        "top_k": top_k,
        "k_effective": k_eff,
        "centroid_sim": round(centroid_sim(hv, hp, mv, mp), 6),
    }

    # для каждого порога считаем precision/recall/f1
    for thr in nn_thresholds:
        t = int(thr * 100)
        r = nn_recall(hp, sim, thr)
        p = nn_precision(mp, sim, thr)
        res[f"recall_{t}"] = round(r, 6)
        res[f"precision_{t}"] = round(p, 6)
        res[f"f1_{t}"] = round(f1_score(p, r), 6)

    return res


# Загрузка и подготовка данных

def load_data():
    """
    Загружает данные людей и делает словарь контекстов
    """
    from filter_data_6 import load_human  # импортим внутри чтоб не было циклических зависимостей
    # filter_data_6 лежит у меня на гитхабе по курсовой, в эссе будет ссылка

    people = load_human()

    # словарь: для каждого слова - его левый контекст
    context_lookup = (
        people.drop_duplicates("word.id")[["word.id", "Left context"]]
        .rename(columns={"word.id": "target_word", "Left context": "left_context"})
    )

    # дедуплицируем ответы людей
    human_deduped = (
        people
        .assign(answer_stripped=people["answer"].str.strip())
        .drop_duplicates(subset=["word.id", "answer_stripped"])
        [["word.id", "answer_stripped", "lemma_answer", "upos_answer", "probability_y"]]
        .dropna(subset=["lemma_answer", "upos_answer"])
    )

    print(f"Загружено людей: {len(human_deduped)} записей, "
          f"{human_deduped['word.id'].nunique()} разных контекстов")

    return human_deduped, context_lookup


def prep_model_df(model_df: pd.DataFrame) -> pd.DataFrame:
    """
    Подготавливаем предсказания модели: дедуплицируем и сортируем по вероятности
    """
    return (
        model_df
        .sort_values("probability_converted", ascending=False)
        .drop_duplicates(subset=["target_word_id", "pred_stripped"], keep="first")
        .dropna(subset=["lemma_word", "upos_word"])
        [["target_word_id", "pred_stripped", "lemma_word",
          "upos_word", "probability_converted"]]
    )





# Основной пайплайн

def run_pipeline(
    approach_name: str,
    get_vec,               # функция, которая возвращает вектор для (лемма, upos, контекст)
    human_deduped: pd.DataFrame,
    model_deduped: pd.DataFrame,
    context_lookup: pd.DataFrame,
    out_dir: Path,
    model_slug: str,
) -> pd.DataFrame:
    """
    Основной пайплайн: обходит все общие контексты и считает метрики
    """
    # находим общие контексты (есть и у людей, и у модели)
    common_ids = sorted(
        set(human_deduped["word.id"]) & set(model_deduped["target_word_id"])
    )
    print(f"  [{approach_name}] Найдено общих контекстов: {len(common_ids)}")

    records = []  # сюда будем складывать результаты

    # идем по каждому контексту
    for i, word_id in enumerate(common_ids):
        if (i + 1) % 20 == 0:
            print(f"    Обработано {i+1}/{len(common_ids)}...", flush=True)

        # берем данные для этого контекста
        h_sub = human_deduped[human_deduped["word.id"] == word_id]
        m_sub = model_deduped[model_deduped["target_word_id"] == word_id]

        if len(h_sub) == 0 or len(m_sub) == 0:
            continue

        # ищем левый контекст
        ctx_row = context_lookup[context_lookup["target_word"] == word_id]
        left_ctx = ctx_row["left_context"].values[0] if len(ctx_row) else ""

        # ── Вектора для людей ──────────────────────────────────────────
        h_vecs = np.array([
            get_vec(r["lemma_answer"], r["upos_answer"], left_ctx)
            for _, r in h_sub.iterrows()
        ])
        h_probs = h_sub["probability_y"].values.astype(float)

        # убираем нулевые вектора
        nonzero_h = h_vecs.any(axis=1)
        if nonzero_h.sum() == 0:
            continue
        h_vecs = h_vecs[nonzero_h]
        h_probs = h_probs[nonzero_h]
        h_probs /= h_probs.sum() + 1e-9

        # ── Вектора для модели (отсортированы по вероятности) ──────
        m_sub_s = m_sub.sort_values("probability_converted",
                                    ascending=False).reset_index(drop=True)
        m_vecs_all = np.array([
            get_vec(r["lemma_word"], r["upos_word"], left_ctx)
            for _, r in m_sub_s.iterrows()
        ])
        m_probs_all = m_sub_s["probability_converted"].values.astype(float)

        # опять убираем нулевые
        nonzero_m = m_vecs_all.any(axis=1)
        if nonzero_m.sum() == 0:
            continue
        m_vecs_all = m_vecs_all[nonzero_m]
        m_probs_all = m_probs_all[nonzero_m]

        # считаем метрики для всех top_k
        for k in top_k_values:
            rec = compute_metrics(h_vecs, h_probs, m_vecs_all, m_probs_all, k)
            rec["word_id"] = word_id
            rec["approach"] = approach_name
            records.append(rec)

    # сохраняем результаты
    df = pd.DataFrame(records)
    fname = out_dir / f"per_context_{approach_name}_{model_slug}.csv"
    df.to_csv(fname, index=False)
    print(f"  Сохранено в {fname.name} ({len(df)} строк)")

    return df